# Generated by Django 4.1.2 on 2022-10-10 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='social_links',
            field=models.URLField(default=''),
        ),
        migrations.AddField(
            model_name='artist',
            name='stage_name',
            field=models.CharField(default='UNKOWN', max_length=255),
        ),
    ]
