# Generated by Django 4.1.2 on 2022-10-10 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0002_artist_social_links_artist_stage_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='social_links',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='artist',
            name='stage_name',
            field=models.CharField(max_length=255),
        ),
    ]
