# Generated by Django 4.1.2 on 2022-10-13 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0004_remove_artist_social_links'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='stage_name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
