# Generated by Django 4.1.2 on 2022-10-13 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0005_alter_artist_stage_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='social_link',
            field=models.URLField(default='\\', max_length=255),
        ),
    ]
