# Generated by Django 4.1.2 on 2022-10-17 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0006_artist_social_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='approved_albums',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='artist',
            name='social_link',
            field=models.URLField(default='', max_length=255),
        ),
    ]
