# Generated by Django 4.1.2 on 2022-10-10 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='New Album', max_length=255)),
                ('creation_datetime', models.DateTimeField()),
                ('release_datetime', models.DateTimeField()),
                ('cost', models.FloatField()),
            ],
        ),
    ]
