# Generated by Django 4.1.2 on 2022-10-17 19:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0004_alter_album_artist'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='is_approved',
            field=models.BooleanField(default=False, help_text='Approve the album if its name is not explicit'),
        ),
        migrations.AlterField(
            model_name='album',
            name='creation_datetime',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
